[[redirects]]
  from = "/api/*"
  to = "https://api.igdb.com/v4/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/news/*"
  to = "https://newsapi.org/v2/:splat"
  status = 200
  force = true
