export { default as Home } from './Home/Home'
export { default as GameDetails } from './GameDetails/GameDetails'
export { default as News } from './News/News'
export { default as GameDirectory } from './GameDirectory/GameDirectory'
export { default as Search } from './Search/Search'